apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gym
  template:
    metadata:
      labels:
        app: gym
    spec:
      containers:
      - name: gym-container
        image: 2024ht66055/appv3:v3
        ports:
        - containerPort: 5000