apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gym
      version: green
  template:
    metadata:
      labels:
        app: gym
        version: green
    spec:
      containers:
      - name: gym-container
        image: 2024ht66055/appv2:v3
        ports:
        - containerPort: 5000